#!/usr/bin/env bash
# Descriptor-based knock provisioning test (run on the Linux build host).
#
# Proves the production client path: a client generated by `gen-client` (no
# bundled gate) enrolls its public key, then knocks a REAL gate using only the
# control plane's gate descriptor (gate knock pubkey, gate_id, suite, addr:port)
# via `knock-descriptor`. The gate authorizes it by thumbprint and the port opens.
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NS=spa-desc-test
PORT=9999
KNOCK_PORT=62201
GW=10.208.0.1
GATE=10.208.0.2
FAILS=0

CLI="$ROOT/target/debug/spa-client"
GATED="$ROOT/spa-gated/target/debug/spa-gated"
OBJ="$ROOT/spa-ebpf/target/bpfel-unknown-none/release/spa-gate"

sudo pkill -9 -f spa-gated 2>/dev/null
sudo pkill -f "http.server $PORT" 2>/dev/null
sudo ip netns del "$NS" 2>/dev/null
sudo ip link del veth0 2>/dev/null

WORK="$(mktemp -d)"
cleanup() {
  sudo pkill -9 -f "spa-gated $WORK" 2>/dev/null
  sudo pkill -f "http.server $PORT" 2>/dev/null
  sudo ip netns del "$NS" 2>/dev/null
  sudo ip link del veth0 2>/dev/null
  rm -rf "$WORK"
}
trap cleanup EXIT

echo "== build =="
( cd "$ROOT/spa-ebpf" && cargo build --release ) || exit 1
( cd "$ROOT" && cargo build -p spa-client ) || exit 1
( cd "$ROOT/spa-gated" && cargo build ) || exit 1

echo "== netns + cloaked listener =="
sudo ip netns add "$NS"
sudo ip link add veth0 type veth peer name veth1
sudo ip link set veth1 netns "$NS"
sudo ip addr add "$GW/24" dev veth0 && sudo ip link set veth0 up
sudo ip netns exec "$NS" ip addr add "$GATE/24" dev veth1
sudo ip netns exec "$NS" ip link set veth1 up
sudo ip netns exec "$NS" ip link set lo up
sudo ip netns exec "$NS" python3 -m http.server "$PORT" --bind "$GATE" >/dev/null 2>&1 &
sleep 1

echo "== gate key + standalone client identity =="
cd "$WORK"
"$CLI" keygen gate >/dev/null
PUB=$("$CLI" gen-client cli | grep public_key_hex | cut -d= -f2)
# Thumbprint = SHA-256(raw pubkey bytes) — the cross-impl contract the control plane uses.
THUMB=$(printf %s "$PUB" | xxd -r -p | sha256sum | cut -d' ' -f1)

GATE_PUB=$(grep '^gate_pubkey_hex=' gate.knock | cut -d= -f2)
GATE_ID=$(grep '^gate_id_hex=' gate.knock | cut -d= -f2)

# What the control plane surfaces as the gate's client descriptor (ports = policy-allowed).
cat > descriptor.json <<EOF
{ "gate_id_hex": "$GATE_ID",
  "gate_pubkey_hex": "$GATE_PUB",
  "suite": "modern",
  "address": "$GATE",
  "knock_port": $KNOCK_PORT,
  "ports": [$PORT] }
EOF

# Gate config authorizes the enrolled client by thumbprint (as a bundle would).
cat > gated.toml <<EOF
interface = "veth1"
knock_port = $KNOCK_PORT
bpf_object = "$OBJ"
pinhole_ms = 1000
skew_seconds = 30
protected_ports = [$PORT]
$(grep -E '^(suite|gate_private_hex|gate_id_hex)' gate.gate.toml)

[[client]]
thumbprint_hex = "$THUMB"
public_key_hex = "$PUB"
ports = [$PORT]
EOF

sudo ip netns exec "$NS" "$GATED" "$WORK/gated.toml" >"$WORK/gated.log" 2>&1 &
sleep 3

connect() { timeout 4 curl --connect-timeout 3 -s -o /dev/null "http://$GATE:$PORT/" && echo CONNECTED || echo BLOCKED; }
assert() { if [ "$2" = "$3" ]; then echo "  PASS: $1"; else echo "  FAIL: $1 (expected $2, got $3)"; FAILS=$((FAILS + 1)); fi; }

echo "== assertions =="
assert "no knock is cloaked" BLOCKED "$(connect)"
# Doc-style 2-arg form: bare prefix (resolves cli.client.key), ports from descriptor.
"$CLI" knock-descriptor "$WORK/descriptor.json" "$WORK/cli" >/dev/null; sleep 0.4
assert "descriptor knock opens the port" CONNECTED "$(connect)"
assert "gate authorized the enrolled client" 1 "$(grep -c '"outcome":"open"' "$WORK/gated.log")"

echo "== daemon decisions =="; grep '"event":"knock"' "$WORK/gated.log" | sed 's/^/  /'
if [ "$FAILS" -eq 0 ]; then echo "== ALL PASS =="; exit 0; else echo "== $FAILS FAILED =="; exit 1; fi
